onboarding = false

[theme]
name = "catppuccin-macchiato"

[terminal]

[update]

[keys]
prefix = "ctrl+a"
settings = "prefix+shift+s"
detach = ["prefix+d", "prefix+q"]
workspace_picker = ["prefix+s", "prefix+w"]
previous_workspace = "prefix+("
next_workspace = "prefix+)"
focus_agent = "prefix+alt+1..9"
rename_tab = "prefix+comma"
previous_tab = "prefix+["
next_tab = "prefix+]"
switch_workspace = "prefix+shift+1..9"
split_vertical = "prefix+backslash"
zoom = "prefix+m"
navigate_workspace_up = "k"
navigate_workspace_down = "j"

[[keys.command]]
key = "prefix+f"
type = "popup"
command = "herdr-sessionizer"
description = "sessionizer (fzf)"
width = "80%"
height = "80%"

[[keys.command]]
key = "prefix+shift+o"
type = "shell"
command = "herdr-sessionizer ~/git"
description = "sessionizer: ~/git"

[[keys.command]]
key = "prefix+shift+w"
type = "shell"
command = "herdr-sessionizer ~/workspace"
description = "sessionizer: ~/workspace"

[[keys.command]]
key = "prefix+shift+v"
type = "shell"
command = "herdr-sessionizer $DOTFILES"
description = "sessionizer: dotfiles"

[ui]
sidebar_width = 32
right_click_passthrough_modifier = "ctrl"
confirm_close = false
prompt_new_tab_name = false
tab_bar_position = "bottom"
agent_panel_sort = "spaces"
show_agent_labels_on_pane_borders = true

[ui.toast]
delivery = "herdr"

[ui.toast.herdr]
position = "top-right"

[ui.sound]

[session]

[remote]

[experimental]
kitty_graphics = true
pane_history = true

[advanced]
scrollback_limit_bytes = 52428800
