font:
  # Normal (roman) font face
  normal:
    family: Fira Mono Nerd Font
    style: Regular

  # Bold font face
  bold:
    family: Fira Mono Nerd Font
    style: Bold

  # Italic font face
  italic:
    family: Fira Mono Nerd Font
    style: Italic

  # Bold italic font face
  bold_italic:
    family: Fira Mono Nerd Font
    style: Bold Italic

  size: 12
  offset:
    x: 0
    y: 0

selection:
  save_to_clipboard: true

cursor:
  style:
    shape: Block
    blinking: On

live_config_reload: true

shell:
  program: /usr/bin/zsh

mouse:
  hide_when_typing: true

window:
  dynamic_title: true
  gtk_theme_variant: dark
  padding:
    x: 2
    y: 0

scrolling:
  history: 10000

colors:
  primary:
    background: '#282a36'
    foreground: '#f8f8f2'
    bright_foreground: '#ffffff'
  cursor:
    text: CellBackground
    cursor: CellForeground
  vi_mode_cursor:
    text: CellBackground
    cursor: CellForeground
  search:
    matches:
      foreground: '#44475a'
      background: '#50fa7b'
    focused_match:
      foreground: '#44475a'
      background: '#ffb86c'
    bar:
      background: '#282a36'
      foreground: '#f8f8f2'
  hints:
    start:
      foreground: '#282a36'
      background: '#f1fa8c'
    end:
      foreground: '#f1fa8c'
      background: '#282a36'
  line_indicator:
    foreground: None
    background: None
  selection:
    text: CellForeground
    background: '#44475a'
  normal:
    black: '#21222c'
    red: '#ff5555'
    green: '#50fa7b'
    yellow: '#f1fa8c'
    blue: '#bd93f9'
    magenta: '#ff79c6'
    cyan: '#8be9fd'
    white: '#f8f8f2'
  bright:
    black: '#6272a4'
    red: '#ff6e6e'
    green: '#69ff94'
    yellow: '#ffffa5'
    blue: '#d6acff'
    magenta: '#ff92df'
    cyan: '#a4ffff'
    white: '#ffffff'
