font:
  # Normal (roman) font face
  normal:
    family: Fira Mono Nerd Font
    style: Regular

  # Bold font face
  bold:
    family: Fira Mono Nerd Font
    style: Bold

  # Italic font face
  italic:
    family: Fira Mono Nerd Font
    style: Italic

  # Bold italic font face
  bold_italic:
    family: Fira Mono Nerd Font
    style: Bold Italic

  size: 12
  offset:
    x: 0
    y: 0

selection:
  save_to_clipboard: true

cursor:
  style:
    shape: Block
    blinking: On

live_config_reload: true

shell:
  program: /usr/bin/zsh

mouse:
  hide_when_typing: true

window:
  dynamic_title: true
  gtk_theme_variant: dark
  padding:
    x: 2
    y: 0

scrolling:
  history: 10000

colors:
  # Default colors
  primary:
    background: '0x1d2021'
    foreground: '0xd5c4a1'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x1d2021'
    cursor: '0xd5c4a1'

  # Normal colors
  normal:
    black:   '0x1d2021'
    red:     '0xfb4934'
    green:   '0xb8bb26'
    yellow:  '0xfabd2f'
    blue:    '0x83a598'
    magenta: '0xd3869b'
    cyan:    '0x8ec07c'
    white:   '0xd5c4a1'

  # Bright colors
  bright:
    black:   '0x665c54'
    red:     '0xfe8019'
    green:   '0x3c3836'
    yellow:  '0x504945'
    blue:    '0xbdae93'
    magenta: '0xebdbb2'
    cyan:    '0xd65d0e'
    white:   '0xfbf1c7'

draw_bold_text_with_bright_colors: false
