font:
  # Normal (roman) font face
  normal:
    family: Fira Mono Nerd Font
    style: Regular

  # Bold font face
  bold:
    family: Fira Mono Nerd Font
    style: Bold

  # Italic font face
  italic:
    family: Fira Mono Nerd Font
    style: Italic

  # Bold italic font face
  bold_italic:
    family: Fira Mono Nerd Font
    style: Bold Italic

  size: 12
  offset:
    x: 0
    y: 0

selection:
  save_to_clipboard: true

cursor:
  style:
    shape: Block
    blinking: On

live_config_reload: true

shell:
  program: /usr/bin/zsh

mouse:
  hide_when_typing: true

window:
  dynamic_title: true
  gtk_theme_variant: dark
  padding:
    x: 2
    y: 0

scrolling:
  history: 10000

colors:
  primary:
    background: '0x282a36'
    foreground: '0xf8f8f2'
  cursor:
    text: CellBackground
    cursor: CellForeground
  vi_mode_cursor:
    text: CellBackground
    cursor: CellForeground
  search:
    matches:
      foreground: '0x44475a'
      background: '0x50fa7b'
    focused_match:
      foreground: '0x44475a'
      background: '0xffb86c'
    bar:
      background: '0x282a36'
      foreground: '0xf8f8f2'
  line_indicator:
    foreground: None
    background: None
  selection:
    text: CellForeground
    background: '0x44475a'
  normal:
    black:   '0x000000'
    red:     '0xff5555'
    green:   '0x50fa7b'
    yellow:  '0xf1fa8c'
    blue:    '0xbd93f9'
    magenta: '0xff79c6'
    cyan:    '0x8be9fd'
    white:   '0xbfbfbf'
  bright:
    black:   '0x4d4d4d'
    red:     '0xff6e67'
    green:   '0x5af78e'
    yellow:  '0xf4f99d'
    blue:    '0xcaa9fa'
    magenta: '0xff92d0'
    cyan:    '0x9aedfe'
    white:   '0xe6e6e6'
  dim:
    black:   '0x14151b'
    red:     '0xff2222'
    green:   '0x1ef956'
    yellow:  '0xebf85b'
    blue:    '0x4d5b86'
    magenta: '0xff46b0'
    cyan:    '0x59dffc'
    white:   '0xe6e6d1'
