import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";

const messages = [
  // Short
  "Schlepping...",
  "Combobulating...",
  "Doing...",
  "Channelling...",
  "Vibing...",
  "Concocting...",
  "Spelunking...",
  "Transmuting...",
  "Imagining...",
  "Pontificating...",
  "Whirring...",
  "Cogitating...",
  "Honking...",
  "Flibbertigibbeting...",
  "Noodling...",
  "Percolating...",
  "Ruminating...",
  "Simmering...",
  "Marinating...",
  "Fermenting...",
  "Gestating...",
  "Hatching...",
  "Brewing...",
  "Steeping...",
  "Contemplating...",
  "Musing...",
  "Pondering...",
  "Mulling...",
  "Daydreaming...",
  "Woolgathering...",
  "Dithering...",
  "Faffing...",
  "Puttering...",
  "Tinkering...",
  "Fiddling...",
  "Noodging...",
  "Finagling...",
  "Wrangling...",
  "Jiggling...",
  "Wiggling...",
  "Shimmying...",
  "Galumphing...",
  "Perambulating...",
  "Meandering...",
  "Traipsing...",
  "Moseying...",
  "Sauntering...",
  "Ambling...",
  "Pottering...",
  "Bumbling...",
  "Futzing...",
  "Schmalzing...",
  "Kerfuffling...",
  "Bamboozling...",
  "Discombobulating...",
  "Recombobulating...",
  "Unbefuddling...",
  "Defenestrating...",
  "Confabulating...",
  "Persnicketing...",
  "Flummoxing...",
  "Befuddling...",
  "Snorkeling...",
  "Yodeling...",
  "Zigzagging...",
  "Ricocheting...",
  "Somersaulting...",
  "Pirouetting...",
  "Canoodling...",
  "Schmoozing...",
  "Kibbitzing...",
  "Skedaddling...",
  "Scampering...",
  "Skittering...",
  "Sashaying...",
  "Swashbuckling...",
  "Oscillating...",
  "Undulating...",
  "Pulsating...",
  "Effervescing...",
  "Fizzing...",
  "Bubbling...",
  "Perplexing...",
  "Mystifying...",
  "Enchanting...",
  "Bewitching...",
  "Beguiling...",
  "Mesmerizing...",
  "Bedazzling...",
  "Sparkling...",
  "Glittering...",
  "Scintillating...",
  "Coruscating...",
  "Phosphorescing...",
  "Luminescing...",
  "Sublimating...",
  "Synthesizing...",
  "Amalgamating...",
  "Procrastinating...",
  "Dillydallying...",
  "Lollygagging...",
  "Dawdling...",
  "Malingering...",
  "Skulking...",
  "Lurking...",
  "Sleuthing...",
  "Rummaging...",
  "Fossicking...",
  "Foraging...",
  "Scavenging...",
  "Absquatulating...",
  "Vamoosing...",
  "Absconding...",
  "Grooving...",
  "Jamming...",
  "Improvising...",
  "Extemporizing...",
  "Freestyling...",
  "Frolicking...",
  "Gamboling...",
  "Blorping...",
  "Flonking...",
  "Snurfling...",
  "Whomping...",
  "Zorping...",
  "Biffing...",
  "Splunging...",
  "Thwacking...",
  "Gonkulating...",
  "Splorfing...",
  "Wibbling...",
  "Wobbling...",
  "Squonking...",
  "Plonking...",
  "Bonking...",
  "Zonking...",
  "Flumping...",
  "Clomping...",
  "Squelching...",
  "Schlurping...",
  "Glurping...",
  "Burbling...",
  "Gurgling...",
  "Splooshing...",
  "Whooshing...",
  "Swooshing...",
  "Kerplunking...",
  "Thunking...",
  "Clunking...",
  "Clanking...",
  "Rattling...",
  "Jostling...",
  "Rustling...",
  "Bustling...",
  "Hustling...",
  "Miffing...",
  "Boffing...",
  "Snazzifying...",
  "Pizzazzing...",
  "Razzmatazzing...",
  "Bedoodling...",
  "Doodling...",
  "Scribbling...",
  "Squiggling...",
  "Wriggling...",
  "Higgling...",
  "Piggling...",
  "Figgling...",
  "Gibbering...",
  "Jabbering...",
  "Blathering...",
  "Blithering...",
  "Withering...",
  "Slithering...",
  "Tethering...",
  "Feathering...",
  "Weathering...",
  "Leathering...",
  "Heathering...",
  "Smoldering...",
  "Moldering...",
  "Shouldering...",
  "Bouldering...",
  "Tottering...",
  "Teetering...",
  "Tittering...",
  "Flittering...",
  "Jittering...",
  "Frittering...",
  "Twittering...",
  "Nattering...",
  "Chattering...",
  "Clattering...",
  "Splattering...",
  "Battering...",
  "Scattering...",
  "Shattering...",
  "Flattering...",
  "Pattering...",
  "Tattering...",
  "Mattering...",
  "Yammering...",
  "Hammering...",
  "Stammering...",
  "Clamoring...",
  "Glamoring...",
  "Enamoring...",
  "Shimmering...",
  "Glimmering...",
  "Brimming...",
  "Skimming...",
  "Trimming...",
  "Primming...",
  "Whimming...",
  "Humming...",
  "Strumming...",
  "Thrumming...",
  "Drumming...",
  "Plumbing...",
  "Thumbing...",
  "Numbing...",
  "Fumbling...",
  "Grumbling...",
  "Mumbling...",
  "Rumbling...",
  "Stumbling...",
  "Tumbling...",
  "Crumbling...",
  "Jumbling...",
  "Humbling...",
  "Bungling...",
  "Jungling...",
  "Mangling...",
  "Wangling...",
  "Dangling...",
  "Tangling...",
  "Jangling...",
  "Angling...",
  "Strangling...",
  "Mingling...",
  "Tingling...",
  "Jingling...",
  "Singling...",
  "Ringling...",
  "Kingling...",
  "Tokenmaxxing...",
  "Bespangling...",
  "Hornswoggling...",
  "Cattywampusing...",
  "Snollygosting...",
  "Taradiddling...",
  "Gobbledygooking...",
  "Mulligrubbing...",
  "Skullduggering...",
  "Shenaniganing...",
  "Tomfoolering...",
  "Malarkeying...",
  "Balderdashing...",
  "Poppycocking...",
  "Codswalloping...",
  "Hogwashing...",
  "Flapdoodling...",
  "Fiddlefaddling...",
  "Widdershinning...",
  "Hocuspocusing...",
  "Abracadabraing...",
  "Alakazaming...",
  "Jiggerypokering...",
  "Nambypambying...",
  "Wishywashing...",
  "Razzledazzling...",
  "Higgledypiggledying...",
  "Ballyhooing...",
  "Hullaballooing...",
  "Brouhahaing...",
  "Fiddledeedeeing...",
  "Hokeypokeying...",
  "Mumbojumboing...",
  "Rigmaroling...",
  "Skedoodling...",
  "Whatchamacalliting...",
  "Thingamajigging...",
  "Doohickeying...",
  "Gizmoing...",
  "Widgeting...",
  "Contraptioning...",
  "Rube-goldberging...",
  "Macgyvering...",
  "Juryrigging...",
  "Kludging...",
  "Hacky-sacking...",
  "Bodge-jobbing...",
  "Fudging...",
  "Wingdinging...",
  "Hootenannying...",
  "Shindigging...",
  "Monadifying...",
  "Functoring...",
  "Currying...",
  "Uncurrying...",
  "Composing...",
  "Pointfreeing...",
  "Eta-reducing...",
  "Beta-reducing...",
  "Memoizing...",
  "Lazifying...",
  "Effect-tracking...",
  "Referentially-transparenting...",
  "Immutabilizing...",
  "Recursing...",
  "Tail-calling...",
  "Pattern-matching...",
  "Destructuring...",
  "Algebraic-data-typing...",
  "Hindley-Milnering...",
  "Lambda-lifting...",
  "Church-encoding...",
  "Y-combinating...",
  "Zippering...",
  "Folding...",
  "Unfolding...",
  "Traversing...",
  "Appling...",
  "Bindifying...",
  "Kleisliing...",
  "Catamorphing...",

  // Long
  "Consulting the void...",
  "Asking the electrons...",
  "Bribing the compiler...",
  "Negotiating with entropy...",
  "Whispering to the bits...",
  "Tickling the stack...",
  "Massaging the heap...",
  "Appeasing the garbage collector...",
  "Summoning semicolons...",
  "Herding pointers...",
  "Untangling spaghetti...",
  "Polishing the algorithms...",
  "Waxing philosophical...",
  "Consulting ancient scrolls...",
  "Reading tea leaves...",
  "Shaking the magic 8-ball...",
  "Sacrificing to the demo gods...",
  "Warming up the hamsters...",
  "Spinning up the squirrels...",
  "Caffeinating...",
  "Existentially questioning...",
  "Having a little think...",
  "Stroking chin thoughtfully...",
  "Squinting at the problem...",
  "Staring into the abyss...",
  "Abyss staring back...",
  "Achieving enlightenment...",
  "Transcending mere computation...",
  "Ascending to a higher plane...",
  "Communing with the machine spirit...",
  "Performing arcane rituals...",
  "Invoking elder functions...",
  "Consulting the oracle...",
  "Divining the answer...",
  "Scrying the codebase...",
  "Dowsing for bugs...",
  "Rearranging deck chairs...",
  "Shuffling bits around...",
  "Aligning the chakras...",
  "Reticulating splines...",
  "Reversing the polarity...",
  "Calibrating the flux capacitor...",
  "Charging the crystals...",
  "Tuning the vibrations...",
  "Adjusting the cosmic frequency...",
  "Waiting for a sign...",
  "Hoping for the best...",
  "Manifesting solutions...",
  "Willing it into existence...",
  "Believing really hard...",
  "Politely asking the CPU...",
  "Bribing the runtime...",
  "Flirting with the database...",
  "Sweet-talking the API...",
  "Negotiating with deadlines...",
  "Having words with the cache...",
  "Reasoning with the memory...",
  "Pleading with the logs...",
  "Bargaining with fate...",
  "Making offerings to the CI...",
  "Praying to the uptime gods...",
  "Consulting the rubber duck...",
  "Interrogating the stack trace...",
  "Cross-examining the debugger...",
  "Petitioning the kernel...",
  "Lobbying the scheduler...",
  "Schmoozing the network...",
  "Buttering up the firewall...",
  "Wining and dining the servers...",
  "Taking the bytes out for lunch...",
  "Giving the code a pep talk...",
  "Reading the room...",
  "Checking under the hood...",
  "Kicking the tires...",
  "Shaking loose the cobwebs...",
  "Dusting off the neurons...",
  "Greasing the gears...",
  "Oiling the cogs...",
  "Winding up the clockwork...",
  "Stoking the furnace...",
  "Feeding the machine...",
  "Watering the logic tree...",
  "Pruning the decision branches...",
  "Harvesting the outputs...",
  "Planting computational seeds...",
  "Nurturing the algorithm...",
  "Raising the exceptions...",
  "Taming wild pointers...",
  "Herding cats in memory...",
  "Teaching old code new tricks...",
  "Whispering sweet nothings to the compiler...",
  "Serenading the syntax...",
  "Dancing with dependencies...",
  "Waltzing through the codebase...",
  "Tangoing with type errors...",
  "Doing the deployment dance...",
  "Having a moment of clarity...",
  "Experiencing a flash of insight...",
  "Channeling the ancient developers...",
  "Receiving transmissions from the cloud...",
  "Asking the hamsters to run faster...",
  "Convincing the pixels to cooperate...",
  "Teaching electrons new tricks...",
  "Bribing the byte fairies...",
  "Whispering passwords to the void...",
  "Negotiating with cosmic rays...",
  "Flattering the floating points...",
  "Seducing the semicolons...",
  "Wooing the while loops...",
  "Charming the curly braces...",
  "Hypnotizing the hash tables...",
  "Mesmerizing the memory banks...",
  "Enchanting the error handlers...",
  "Bewitching the boolean logic...",
  "Spellbinding the stack frames...",
  "Hexing the hexadecimals...",
  "Jinxing the JSON parsers...",
  "Cursing the cache misses...",
  "Blessing the build process...",
  "Anointing the algorithms...",
  "Consecrating the callbacks...",
  "Sanctifying the source code...",
  "Exorcising the exceptions...",
  "Purifying the parameters...",
  "Cleansing the closures...",
  "Baptizing the binary...",
  "Absolving the abstractions...",
  "Redeeming the recursion...",
  "Forgiving the for loops...",
  "Pardoning the pointers...",
  "Liberating the lambdas...",
  "Emancipating the enums...",
  "Freeing the functions...",
  "Releasing the references...",
  "Unbinding the variables...",
  "Untying the type knots...",
  "Unraveling the regex...",
  "Decoding the mysteries...",
  "Cracking the conundrums...",
  "Solving the riddles of RAM...",
  "Unlocking the secrets of silicon...",
  "Discovering hidden semicolons...",
  "Unearthing buried bugs...",
  "Excavating ancient APIs...",
  "Archeologically analyzing the architecture...",
  "Fossil hunting in the functions...",
  "Spelunking through the stack...",
  "Scuba diving in the data...",
  "Snorkeling through the streams...",
  "Parasailing past the parameters...",
  "Hang gliding through the heap...",
  "Bungee jumping into the backend...",
  "Skydiving through the source...",
  "Surfing the syntax waves...",
  "Skateboarding down the stack trace...",
  "Snowboarding through the schemas...",
  "Mountain climbing the modules...",
  "Hiking through the headers...",
  "Trekking through the trees...",
  "Backpacking through the binaries...",
  "Camping in the codebase...",
  "Glamping in the globals...",
  "Picnicking with the processes...",
  "Barbecuing the bugs...",
  "Roasting the race conditions...",
  "Grilling the glitches...",
  "Sautéing the syntax errors...",
  "Flambéing the failures...",
  "Caramelizing the callbacks...",
  "Braising the breakpoints...",
  "Poaching the pointers...",
  "Blanching the branches...",
  "Searing the segments...",
  "Smoking the subroutines...",
  "Curing the code smells...",
  "Pickling the packages...",
  "Preserving the protocols...",
  "Canning the constants...",
  "Bottling the buffers...",
  "Jarring the JavaScript...",
  "Decanting the data structures...",
  "Aerating the arrays...",
  "Letting the logic breathe...",
  "Aging the algorithms gracefully...",
  "Maturing the methods...",
  "Ripening the results...",
  "Seasoning the solutions...",
  "Spicing up the specs...",
  "Garnishing the getters...",
  "Plating the output nicely...",
  "Presenting with pizzazz...",
  "Adding a dash of elegance...",
  "Sprinkling some magic dust...",
  "Drizzling debug sauce...",
  "Folding in the features...",
  "Whisking the widgets...",
  "Kneading the namespaces...",
  "Rolling out the runtime...",
  "Proofing the promises...",
  "Letting the dough rise...",
  "Baking at 350 kilobytes...",
  "Frosting the functions...",
  "Decorating the deployment...",
  "Icing the interfaces...",
  "Glazing the graphics...",
  "Topping with tests...",
  "Cherry-picking the commits...",
  "Slop forking open source...",
  "Convincing the linter to chill...",
  "Apologizing to the type checker...",
  "Holding a seance for deleted code...",
  "Hosting a town hall for the tabs...",
  "Mediating a dispute between spaces...",
  "Sending thoughts and prayers to prod...",
  "Checking if the servers are still friends...",
  "Asking DNS for directions...",
  "Leaving a voicemail for the monolith...",
  "Writing a strongly worded letter to latency...",
  "Filing a complaint with the event loop...",
  "Scheduling a 1:1 with the garbage collector...",
  "Giving the mutex a pep talk...",
  "Tucking the threads in for a nap...",
  "Reading bedtime stories to the daemons...",
  "Braiding the call stacks...",
  "Ironing the wrinkled state...",
  "Folding the laundry of technical debt...",
  "Sorting the sock drawer of side effects...",
  "Dusting the forgotten TODOs...",
  "Watering the houseplant of hope...",
  "Fluffing the pillows of the happy path...",
  "Vacuuming under the couch of edge cases...",
  "Mopping up spilled exceptions...",
  "Polishing the doorknobs of the API...",
  "Hanging curtains on the public interface...",
  "Arranging flowers in the feature flags...",
  "Lighting candles for the flaky tests...",
  "Burning sage in the staging environment...",
  "Ringing a tiny bell for each resolved TODO...",
  "Counting the sheep in the thread pool...",
  "Naming the clouds in the distributed system...",
  "Petting the wild goroutines...",
  "Walking the race conditions on a leash...",
  "Feeding treats to well-behaved assertions...",
  "Scratching the ears of the event bus...",
  "Teaching the cache to fetch...",
  "Showing the queue how to wait its turn...",
  "Reminding the retry loop that patience is a virtue...",
  "Telling the infinite loop a bedtime story...",
  "Introducing the frontend to the backend...",
  "Hosting a mixer for microservices...",
  "Passing notes between the containers...",
  "Starting a book club for the design docs...",
  "Organizing a potluck for the plugins...",
  "Knitting a cozy for the cold start...",
  "Crocheting a blanket for the bare metal...",
  "Origami-folding the configuration...",
  "Building a tiny fort out of stack frames...",
  "Making friendship bracelets for the dependencies...",
  "Asking the monad what it wants to be when it grows up...",
  "Gently unwrapping the Maybe...",
  "Politely declining the null...",
  "Folding the list into a single beautiful thought...",
  "Mapping over the possibilities...",
  "Filtering out the impure thoughts...",
  "Reducing the problem to its essence...",
  "Composing pure functions like a bouquet...",
  "Currying favor with the type system...",
  "Point-freeing until nothing remains but truth...",
  "Eta-reducing the unnecessary ceremony...",
  "Beta-reducing towards enlightenment...",
  "Memoizing the vibes for later...",
  "Lazily evaluating whether to care...",
  "Thunking about it carefully...",
  "Preserving referential transparency at all costs...",
  "Refusing to mutate on principle...",
  "Recursing until the base case shows mercy...",
  "Trusting the tail call to do the right thing...",
  "Pattern matching on the shape of reality...",
  "Destructuring the problem into named pieces...",
  "Summoning an algebraic data type from the void...",
  "Letting Hindley-Milner figure it out...",
  "Church-encoding the integers for fun...",
  "Applying the Y combinator with great ceremony...",
  "Zippering two infinite lists together carefully...",
  "Catamorphing the recursive structure into soup...",
  "Kleisli-composing my way out of this mess...",
  "Binding through the Either of hope and despair...",
  "Lifting a pure value into the effectful world...",
  "Aping the Applicative for sequential delight...",
  "Traversing the structure with good intentions...",
  "Fusing the maps to please the optimizer...",
  "Deforesting the intermediate lists...",
  "Proving it correct by construction...",
  "Making illegal states unrepresentable...",
  "Encoding the business rules in the types...",
  "Letting the compiler do the thinking...",
  "Trading runtime errors for compile-time vibes...",
  "Preferring total functions to partial excuses...",
];

function pickRandom(): string {
  return messages[Math.floor(Math.random() * messages.length)]!;
}

export default function (pi: ExtensionAPI) {
  pi.on("turn_start", async (_event, ctx) => {
    ctx.ui.setWorkingMessage(pickRandom());
  });

  pi.on("turn_end", async (_event, ctx) => {
    ctx.ui.setWorkingMessage(); // Reset for next time
  });
}
