"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

[directory]
truncate_to_repo = false

[character]
success_symbol = '[󰘧](bold green) '
error_symbol = '[󰘧](bold red) '

[lua]
symbol = " "

[elixir]
symbol = " "

[buf]
disabled = true
